version: '3.9'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tax_database
      POSTGRES_USER: tax_assistant
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"  # Expose PostgreSQL to host
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
#docker-compose build
#docker-compose up -d
